### ISSUE TITLE
CCID2014 database

### ISSUE THREAD

**Issue by YANGXDo** [mtobeiyf/CEIQ#2]
It's a great honor to read your article.  But unfortunately, I can't find the CCID2014 database. Could you please provide me with the download link?  Thanks a lot.

**Comment by imfing** [comment]
I think CCID2014 was from the paper: Ke Gu, Guangtao Zhai, Weisi li, Min Liu, “The analysis of image contrast: From quality assessment to automatic enhancement,” IEEE Transactions on Cybernetics (T-CYB), 2016
The author of that paper, [Ke Gu](https://kegu.netlify.app/) provided the [database](https://mega.nz/#!1wtGEBAJ!KSEGc3Q93gSTemq7hwmCRaTNSpReoFxEJ1JnVholACs) on his home page.
